### ISSUE TITLE
Special characters (non ASCII) from lyrics are dropped when saved to the sqlite db

### ISSUE THREAD

**Issue by benotn** [mihaiolteanu/versuri#5]
Hi,

as the title says, characters such as é and ñ are not saved in the sqlite database, but are instead dropped.
See for example lyrics for "La Vida Tombola" from "Manu Chao":
First sentence after saving: "Si yo fuera Maradona, vivira como l" (instead of "Si yo fuera Maradona, vivira como él").

I replaced the esqlite package with emacsql and emacsql-sqlite3 package (AFAIK more actively maintained) and rewrote the affected parts, which solves this issue.
If you are interested, I can open up a PR for this?

**Comment by mihaiolteanu** [comment]
Hello Benjamin,

I cannot reproduce your issue.
I've run `(versuri-display "Manu Chao" "La Vida Tombola")` once to save the lyrics in the db and display them in a new buffer.

The db looks like this after the call,
![Screenshot from 2021-01-04 13-06-58](https://user-images.githubusercontent.com/8273519/103529170-db357100-4e8d-11eb-9b97-3edf0d8e3861.png)


On subsequent calls, when the lyrics are taken from the db, the buffer looks like this,
![Screenshot from 2021-01-04 13-08-51](https://user-images.githubusercontent.com/8273519/103529261-061fc500-4e8e-11eb-9f0b-4ed48b6a9f2e.png)

**Comment by benotn** [comment]
Hi, I checked this again and it was an error of the sqlite3 binary.
With the faulty one (3.33.0 2020-08-14 13:23:32 fca8dc8b578f215a969cd899336378966156154710873e68b3d9ac5881b0alt2) I experienced the issue and with a current one (3.35.5 2021-04-19 18:32:05 1b256d97b553a9611efca188a3d995a2fff712759044ba480f9a0c9e98fae886) I don't.
